[package]
name = "arb-util"
version = "0.1.0"
edition = "2024"

[dependencies]
notify = "8.2.0"
serde_yaml = "0.9.34"
serde = { version = "1.0", features = ["derive"] }
regex = "1.12.3"
serde_json = "1.0.149"
rayon = "1.11.0"
